# Generated by Django 4.1.1 on 2023-10-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricians',
            name='cities',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
